export class ErrMessageUtilsTH{

    messageSucceessEn = 'Success'
    messageSuccess ='เรียบร้อย'
    messageProcessFail = 'ล้มเหลว'

    errLoginUserOrPasswordNotValid = 'Username หรือ Password ไม่ถูกต้อง'
    errLoginFail = 'เข้าสู่ระบบล้มเหลว'
    errUsernameNotFound = 'กรุณากรอก Username'
    errUsernameProhibitSpecial = 'Username ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errPasswordNotFound = 'กรุณากรอก Password'
    errPasswordProhibitSpecial = 'Password ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errRecordInNotFound = 'ไม่พบข้อมูลการทำรายการเข้า'

    errCompanyIDNotFound = 'ไม่พบรหัสหมู่บ้าน'
    errCompanyIDNotNumber = 'รหัสหมู่บ้านต้องเป็นตัวเลขเท่านั้น'
    errCompanyIDProhibitSpecial = 'รหัสหมู่บ้านห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCompanyCodeProhibitSpecial = 'โค้ดหมู่บ้านห้ามีอักขระพิเศษ หรือช่องว่าง'
    errCompanyNotInBase = 'ไม่พบหมู่บ้านในระบบ'
    errGuardHouseIDNotFound = 'ไม่พบรหัสป้อม'
    errGuardHouseIDNotNumber = 'รหัสป้อมต้องเป็นตัวเลขเท่านั้น'
    errGuardHouseIDProhibitSpecial = 'รหัสป้อมห้ามมีอักชระพิเศษ หรือช่องว่าง'
    errGuardHouseCodeProhibitSpecial = 'โค้ดป้อมห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errVisitorSlotRunningIdNotFound = 'ไม่พบ visitor_slot_running_id'
    errVisitorSlotRunningIdNotNumber = 'visitor_slot_running_id ต้องเป็นตัวเลขเท่านั้น'
    errVisitorCartypeIDNotfound = 'ไม่พบรหัสประเภทรถ'
    errVisitorCartypeIDProhibitSpecail = 'รหัสประเภทรถห้ามมีอักขระพิเศษ'
    errVisitorCartypeIDNotNumber = 'รหัสประเภทรถต้องเป็นตัวเลขเท่านั้น'
    errVisitorCartypeNameContractionNotFound = 'ไม่พบอักษรย่อของประเภทรถ'
    errVisitorCartypeNameContractionProhibitSpecial ='อักษรย่อของประเภทรถ ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorCartypeNameThNotFound = 'ไม่พบประเภทรถ (ชื่อไทย)'
    errVisitorCartypeNameThProhibitSpecial = 'ประเภทรถ (ชื่อไทย) ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorCartypeNameEnNotFound = 'ไม่พบประเภทรถ (ชื่ออังกฤษ)'
    errVisitorCartypeNameEnProhibitSpecial = 'ปรเภทรถ (ชื่ออังกฤษ) ห้ามมีอักขระพิเศษหรือช่องว่าง'

    errVisitorRecordIdNotFound = 'ไม่พบรหัส Visitor record'
    errVisitorRecordIdProhibitSpecial = 'Visitor record ห้ามมีอักระพิเศษ หรือช่องว่าง'
    errVisitorRecordIdNotNumber = 'Visitor record ต้องเป็นตัวเลขเท่านั้น'

    errVisitorRecord_CodeNotFound = 'ไม่พบโค้ด Visitor record'
    errVisitorRecord_CodeProhitbit = 'โค้ด Visitor record ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errVisitorInfoNotFound = 'ไม่พบข้อมูลของ Visitor'
    errVisitorInfoPrefixNameNotFound = 'ไม่พบคำนำหน้าชื่อ Visitor'
    errVisitorInfoPrefixNameProhibitSpecial = 'คำนำหน้าชื่อ Visitor ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorInfoFirstNameNotFound = 'ไม่พบชื่อของ Visitor'
    errVisitorInfoFirstNameProhibitSpecial = 'ชื่อของ Visitor ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorInfoLastNameNotFound = 'ไม่พบนามสกุลของ Visitor'
    errVisitorInfoLastNameProhibitSpecial = 'นามสกุลของ Visiotr ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorInfoBirthDateNotFound = 'ไม่พบวัน-เดือน-ปี เกิด ของ Visitor'
    errVisitorInfoIdentityNotFound = 'ไม่พบรหัสประจำตัวประชาชน'
    errVisitorInfoIdentityNotNumber = 'รหัสประจำตัวประชาชนต้องเป็นตัวเลขเท่านั้น'
    errVisitorInfoIdentityFormatNotValid = 'รูปแบบรหัสประชำตัวประชาชนไม่ถูกต้อง'

    errEmployeeIDNotFound = 'ไม่พบไอดีพนักงาน'
    errEmployeeIDNotNumber = 'ไอดีพนักงานต้องเป็นตัวเลขเท่านั้น'
    errEmployeeIDProhibitSpecail = 'ไอดีพนักงานห้ามมีอักขระพิเศษ'
    errEmployeeIDNotInDatabase = 'ไม่พบพนักงานในระบบ'
    errEmployeeCodeNotFound = 'ไม่พบรหัสพนักงาน'
    errEmployeeFirstNameNotFound = 'ไม่พบชื่อพนักงาน'
    errEmployeeFitstNameProhibitSpecial = 'ชื่อพนักงาน ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errEmployeeLastNameNotFound = 'ไม่พบนามสกุลพนักงาน'
    errEmployeeLastNameProhibitSpecial = 'นามสกุลพนักงาน ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errEmployeeInfoNotFound = 'ไม่พบข้อมูลพนักงาน'

    errGetSlotVisitorNumberCompanyIDNotFound = 'ไม่พบ company id'
    errGetSlotVisitorNumberCompanyIDProhibitSpecial = 'company id ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errGetSlotVisitorNumberCompanyIDNotNumber ='company id ต้องเป็นตัวเลขเท่านั้น'
    errGetSlotVisitorNumberSlotNumberNotFound = 'ไม่พบเลข Slot'
    errGetSlotVisitorNumberSlotNumberProhibitSpecial = 'เลข Slot ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errGetSlotVisitorNumberSlotNumberNotNumber ='เลข Slot ต้องเป็นตัวเลขเท่านั้น'
    errGetSlotVisitorNumberIsFail = 'ค้นหา slot ล้มเหลว'
    errGetSlotVistiorNumberNotValue = 'ไม่พบ Slot ว่าง'
    errGetSlotVisitorNumberNotInDataBase = 'ไม่พบเลข slot ในระบบ'
    errGetSlotVisitorNumberIsDuplicate = 'เลข slot ถูกใช้งานไปแล้ว'
    errGetSlotVisitorNumberIsNotCheckIn = 'เลข slot นี้ยังไม่ได้ทำรายการเข้า'

    errVisitorSlotIdNotFound = 'ไม่พบ record id ของขาเข้า'
    errVisitorSlotIdNotNumber = 'record id ต้องเป็นตัวเลขเท่านั้น'
    errVisitorSlotIdProhibitSpecial = 'record id ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errGetCardOrSlotNumberVisitor = 'กรุณาเลือกกรอกเลขบัตร หรือเลข slot อย่างใดอย่างหนึ่ง'
    
    errGetHaveCardCodeAndCardName = 'กรุณาเลือกกรอกเลขบัตร หรือทาบบัตร อย่างใดอย่างหนึ่ง'
    errGetCardNotNumber = 'เลขบัตรต้องเป็นตัวเลขเท่านั้น'
    errGetCardProhibitSpecial = 'เลขบัตรห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errGetCardNotInDatabase = 'ไม่พบบัตรในระบบ'
    errGetCardIsDuplicate = 'บัตรยังไม่ได้ทำรายการออก'
    errGetCardIsNotCheckIn = 'บัตรยังไม่ได้ทำรายการเข้า'
    errGetCardIDIsFail = 'ค้นหาบัตรล้มเหลว'

    errVisitorRecordIDNotFound = 'ไม่พบรหัสอ้างอิง'
    errVisitorRecordInNotFound = 'ไม่พบข้อมูลขาเข้า'

    

    errImageNotFound = 'ไม่พบรูปภาพ';
    errImageCardNotFound = 'ไม่พบรูปภาพหน้าบัตร'
    errImageVehicleNotFound = 'ไม่พบรูปภาพพาหนะ'
    errImageCustomerNotFound = 'ไม่พบรูปภาพผู้ใช้บริการ'
    errImageParcelNotFound = 'ไม่พบรูปภาพพัสดุ'

    errHomeIDNotFound = 'ไม่พบรหัสที่อยู่'
    errHomeIDNotNumber = 'รหัสที่อยู่ต้องเป็นตัวเลขเท่านั้น'
    errHomeIdProhibitSpecial = 'รหัสที่อยู่ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errHomeIDNotInDataBase = 'ไม่พบบ้านเลขที่ในระบบ'
    errHomeGetFail = 'เรียกดูข้อมูลบ้านล้มเหลว'

    errGetCompanyIDNotFound = 'ไม่พบรหัส Company'
    errGetCompanyIDNotNumber = 'รหัส Company ต้องเป็นตัวเลขเท่านั้น'
    errGetCompanyIDProhibitSpecial = 'รหัส Company ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    
    errGetGuardhouseIDNotFound = 'ไม่พบรหัสป้อม'
    errGetGuardhouseIDNotNumber = 'รหัสป้อมต้องเป็นตัวเลขเท่านั้น'
    errGetGuardhouseIDProhibitSpecial = 'รหัสป้อม ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errGetCarTypeFail = 'เรียกดูประเภทรถล้มเหลว'
    errGetCarTypeNotFound = 'ไม่พบรหัสประเภทรถ'
    errGetCarTypeNotNumber = 'รหัสประเภทรถต้องเป็นตัวเลขเท่านั้น'
    errGetCarTypeProhibitSpecial = 'รหัสประเภทรถห้ามมีอักขระพิเศษ หรือช่องว่าง'
   
    errGetCartypeCategoryFail = 'เรียกดูหมวดหมู่รถล้มเหลว'

    errGetDataActionInInfoNotFound = 'ไม่พบข้อมูลขาเข้า'

    errImagePathNotFound = 'กรุณาใส่ Path รูปภาพ'
    errImageGetFail = 'ไม่พบรูปภาพที่ร้องขอ'
    
    errAuthorizationNotFound = 'ไม่พบ Bearer Token สำหรับร้องขอข้อมูล'

    errPosIDNotFound = 'ไม่พบ pos id'
    errPosIDProhibitSpecial = 'pos id ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errPriceOfCardlossNotFound = 'ไม่พบค่าปรับบัตรหาย'
    errPriceOfCardlossProhibitSpecial = 'ค่าปรับบัตรหายห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errPriceOfCardlossNotNumber  = 'ค่าปรับบัตรหายต้องเป็นตัวเลขเท่านั้น'

    errCustomerPaymentNotFound = 'ไม่พบจำนวนเงินที่ลูกค้าชำระบริการ'
    errCustomerPaymentProhibitSpecial = 'จำนวนเงินที่ลูกค้าชำระบริการห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCustomerPaymentNotNumber  = 'จำนวนเงินที่ลูกค้าชำระบริการต้องเป็นตัวเลขเท่านั้น'

    errChangeMoneyNotFound = 'ไม่พบจำนวนเงินทอน'
    errChangeMoneyProhibitSpecial = 'จำนวนเงินทอนห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errChangeMoneyNotNumber  = 'จำนวนเงินทอนต้องเป็นตัวเลขเท่านั้น'

    errPaymentIncomplete = 'ชำระเงินไม่ครบถ้วน'

    errCardlossCardIDBeforeNotFound = 'ไม่พบ ID ของบัตรที่หาย'
    errCardlossCardIDBeforeProhibitSpecial = 'ID ของบัตรที่หายห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCardlossCardIDBeforeNotNumber = 'ID ของบัตรหายต้องเป็นตัวเลขเท่านั้น'
    errCardlossCardCodeBeforeNotFound = 'ไม่พบรหัสบัตรที่หาย'
    errCardlossCardCodeBeforeProhibitSpecial = 'รหัสบัตรที่หายห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCardlossCardCodeBeforeNotNumber = 'รหัสบัตรหายต้องเป็นตัวเลขเท่านั้น'
    errCardlossCardNameBeforeNotFound = 'ไม่พบเลขบัตรที่หาย'
    errCardlossCardNameBeforeProhibitSpecial = 'เลขบัตรที่หายห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCardlossCardNameBeforeNotNumber = 'เลขบัตรหายต้องเป็นตัวเลขเท่านั้น'
    errCardLossCardBeforeIsNotCheckIn = 'บัตรที่หายไม่ได้ทำรายการเข้า'
    errCardLossCardBeforeNotInDatabase = 'ไม่พบข้อมูลบัตรที่หายอยู่ในระบบ'

    errCardlossCardIDAfterNotFound = 'ไม่พบ ID ของบัตรใหม่'
    errCardlossCardIDAfterProhibitSpecial = 'ID ของบัตรใหม่ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCardlossCardIDAfterNotNumber = 'ID ของบัตรใหม่ต้องเป็นตัวเลขเท่านั้น'
    errCardlossCardCodeAfterNotFound = 'ไม่พบรหัสบัตรใหม่'
    errCardlossCardCodeAfterProhibitSpecial = 'รหัสของบัตรใหม่ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCardlossCardCodeAfterNotNumber = 'รหัสของบัตรใหม่ต้องเป็นตัวเลขเท่านั้น'
    errCardlossCardNameAfterNotFound = 'ไม่พบเลขบัตรใหม่'
    errCardlossCardNameAfterProhibitSpecial = 'เลขบัตรใหม่ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCardlossCardNameAfterNotNumber = 'เลขบัตรใหม่ต้องเป็นตัวเลขเท่านั้น'
    errCardLossCardAfterNotInDatabase = 'ไม่พบข้อมูลบัตรใหม่อยู่ในระบบ'
    errCardLossCardAfterIsNotCheckIn = 'บัตรใหม่ถูกงานใช้อยู่แล้ว'

    errVisitorRecordCodeNotFound = 'ไม่พบ uuid สำหรับขอพิมพ์ใบเสร็จ'
    errSlipInGetNotRow = 'ไม่พบข้อมูลขาเข้า'

    errฺBookingTbvCodeNotFound = 'ไม่พบ QR Code จากการจอง'
    errฺBookingTbvCodeProhibitSpecial = 'QR Code ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errBookingNotFound = 'ไม่พบข้อมูลการจอง หรือหมดเวลาจองไปแล้ว'
    errBookingQRNotFound = 'ไม่พบ QR Code ในระบบ'
    errBookingQRCodeNotIn = 'QR Code ไม่ได้ทำรายการเข้า'

    errBookingGetError = 'ตรวจสอบ Booking Error กรุณาติดต่อเจ้าหน้าที่'
    errBookingNotVerifyEstamp = 'ไม่พบการ E-Stamp จากลูกบ้าน'
    
    errHomeAddressNotFound = 'กรุณากรอกที่อยู่'
    errHomeAddressProhibitSpecial = 'ที่อยู่ห้ามมีอักขระพิเศษ'
    errHomeAddressIsDuplicate = 'บ้านเลขที่ซ้ำในระบบ'
    errHomeAddressNotInBase = 'ไม่พบที่อยู่ในระบบ'

    errFirstNameNotFound = 'กรุณากรอกชื่อ'
    errFirstNameProhitbitSpecial = 'ชื่อห้ามมีอักขระพิเศษ'
    errLastNameNotFound = 'กรุณากรอกนามสกุล'
    errLastNameProhitbitSpecial = 'นามสกุลห้ามมีอักขระพิเศษ'
    errMobilePhoneNotFound = 'กรุณากรอกเบอร์โทรศัพท์'
    errMobilePhoneProhitbitSpecial = 'เบอร์โทรศัพท์ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errMobilePhoneNotNumber = 'เบอร์โทรศัพท์ต้องเป็นตัวเลขเท่านั้น'

    errVillagerNotFound = 'ไม่พบรหัสของลูกบ้าน'
    errVillagerProhibitSpecial = 'รหัสลูกบ้านห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errVillagerNotNumber = 'รหัสลูกบ้านต้องเป็นตัวเลขเท่านั้น'
    errVillagerNotInBase = 'ไม่พบข้อมูลลูกบ้านในระบบ'

    errAnnounceNameNotFound = 'ไม่พบชื่อเรื่องประกาศ'
    errAnnounceNameProhibitSpecial = 'ชื่อเรื่องประกาศห้ามมีอักขระพิเศษ'
    errAnnounceHeaderNotFound = 'ไม่พบหัวข้อประกาศ'
    errAnnounceHeaderProhitbitSpecial = 'หัวข้อประกาศห้ามมีอักขระพิเศษ'
    errAnnounceDetailNotFounce = 'ไม่พบรายละเอียดของประกาศ'
    errAnnounceDetailProhibitSpecial = 'รายละเอียดของประกาศห้ามมีอักขระพิเศษ'
    errAnnounceNotInBase = 'ไม่พบประกาศในระบบ'
    errAnnounceIDNotFound = 'ไม่พบรหัสอ้างอิงประกาศ'
    errAnnounceIDProhibitSpecial = 'รหัสอ้างอิงประกาศห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errAnnounceIDNotNumber = 'รหัสอ้างอิงประกาศต้องเป็นตัวเลขเท่านั้น'

    errAnnounceValueNotFound = 'ไม่พบจำนวนที่ใช้ในการค้นหาประวัติของประกาศโครงการ'
    errAnnounceValueProhibitSpecial = 'จำนวนที่ใช้ในการค้นหาประวัติของประกาศโครงการ ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errAnnounceValueNotNumber = 'จำนวนที่ใช้ในการค้นหาประวัติของประกาศโครงการ ต้องเป็นตัวเลขเท่านั้น'
    errAnnounceTypeNotFound = 'ไม่พบประเภทที่ใช้ในการค้นหาประวัติของประกาศโครงการ'
    errAnnounceTypeProhibitSpecial = 'ประเภทที่ใช้ในการค้นหาประวัติของประกาศโครงการ ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errLicensePlateProhitbitSpecial = 'ทะเบียนรถห้ามมีอักขระพิเศษ'

    errEstampNotInBase = 'ไม่พบตราประทับในระบบ'
    errEstampNotFound = 'ไม่พบการประทับตรา'
    errEstampProhibitSpecial = 'การประทับตรา ห้ามมีอักขระพิเศษ หรือช่องว่าง'

    errVisitorRecordNotIn = 'ไม่พบการทำรายการเข้านี้'
    errVisitorEstamped = 'Visitor ได้ทำรายการประทับตราแล้ว'

    errComplaintIDNotfound = 'ไม่พบรหัสร้องเรียน'
    errComplaintIDProhibitSpecial = 'รหัสร้องเรียนห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errComplaintIDNotNumber = 'รหัสร้องเรียนต้องเป็นตัวเลขเท่านั้น'
    errComplaintNotInBase = 'ไม่พบการร้องเรียนในระบบ'
    errComplaintHeaderProhibitSpecial = 'หัวข้อร้องเรียนห้ามมีอักขระพิเศษ'

    errComplaintRemarkNotFound = 'ไม่พบข้อความแจ้งเตือนลูกค้า'
    errComplaintRemarkProhitbitSpecial = 'ข้อความแจ้งเตือนลูกค้า ห้ามมีอักขระพิเศษ'

    errTimeStartNotFound = 'ไม่พบเวลาเริ่มต้นในการค้นหา'
    errTimeStartNotTimeFormat = 'รูปแบบเวลาเริ่มต้นในการค้นหาไม่ถูกต้อง'
    errTimeEndNotFound = 'ไม่พบเวลาสิ้นสุดในการค้นหา'
    errTimeEndNotTimeFormat = 'รูปแบบเวลาสิ้นสุดในการค้นหาไม่ถูกต้อง'
    errTimeStartOverTimeEnd = 'เวลาค้นหาเริ่มต้น ต้องน้อยกว่าเวลาค้นหาสิ้นสุด'
    errTimeSearchOver30Days = 'ช่วงเวลาที่ใช้ค้นหา ห้ามเกิน 30 วัน'

    errDateFormNotFound = 'ไม่พบวันที่เริ่มต้น'
    errDateFormNotTimeFormat = 'รูปแบบวันที่เริ่มต้น ไม่ถูกต้อง'
    errDateToNotFound = 'ไม่พบวันที่สิ้นสุด'
    errDateToNotTimeFormat = 'รูปบบวันที่สิ้นสุด ไม่ถูกต้อง'
    errDateFormIsOverDateTo = 'วันที่เริ่มต้น ต้องน้อยกว่าวันที่สิ้นสุด'

    errParcelReceiveTitleNotFound = 'กรุณาระบุหัวข้อการรับพัสดุ'
    errParcelReceiveTitleProhitbitSpecial = 'หัวข้อการรับพัสดุ ห้ามมีอักขระพิเศษ'
    errParcelRecieveDetailProhibitSpecial = 'รายละเอียดการรับพัสดุ ห้ามมีอักขระพิเศษ'
    errReceiveParcelDetailNotFound = 'กรุณาระบุรายละเอียดของพัสดุ'
    errRecieveParcelDetailProhibitSpecial = 'รายะละเอียดของพัสดุ ห้ามมีอักขระพิเศษ'
    errSendParcelDetailNotfound = 'กรุณาระบุรายละเอียดการส่งมอบพัสดุ'
    errSendParcelDetailProhitbitSpecial = 'ละเอียดการส่งมอบพัสดุ ห้ามมีอักขระพิเศษ'

    errParcelIDNotFound = 'ไม่พบรหัสพัสดุ'
    errParcelIDProhitbitSpecial = 'รหัสพัสดุ ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errParcelIDNotNumber = 'รหัสพัสดุต้องเป็นตัวเลขเท่านั้น'
    errParcelNotInBase = 'ไม่พบรหัสพัสดุในระบบ'
    errParcelSuccessfully = 'ลูกบ้านทำรายการรับพัสดุแล้ว'
    errParcelReject = 'รายการรับพัสดุถูกยกเลิกไปแล้ว'
    errParcelSending = 'พัสดุถูกส่งให้ลูกบ้านแล้ว'
    errParcelNotSendedStatus= 'พัสดุยังไม่ถูกส่งให้ลูกบ้าน'

    errSosIdNotfound = 'ไม่พบรหัสแจ้งเตือนฉุกเฉิน'
    errSosIdProhibitSpecial = 'รหัสแจ้งเตือนฉุกเฉิน ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errSosIdNotNumber = 'รหัสแจ้งเตือนฉุกเฉินต้องเป็นตัวเลขเท่านั้น'
    errSosNotInbase = 'ไม่พบการแจ้งเตือนฉุกเฉินในระบบ'
    errSosActionDuplicate = 'การแจ้งเตือนฉุกเฉินถูกอนุมัติไปแล้ว'

    errRemarkNofound = 'กรุณากรอกหมายเหตุ'
    errReamrkPohibitSpecial = 'หมายเหตุ ห้ามมีอักขระพิเศษ'

    errSquareValueNotfound = 'กรุณากรอกราคาต่อหน่วย'
    errSquareValueProhibitSpecial = 'ราคาต่อหน่วย ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errSquareValueNotNumber = 'ราคาต่อหน่วย ต้องเป็นตัวเลขเท่านั้น'
    errCommonPaymentAmountNotFound = 'กรุณากรอกค่าส่วนกลาง'
    errCommonPaymentAmountProhibitSpecial = 'ค่าส่วนกลางห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCommonPaymentAmountNotNumber = 'ค่าส่วนกลาง ต้องเป็นตัวเลขเท่านั้น'
    errCommonFeeNotInBase = 'ไม่พบข้อมูลค่าส่วนกลางในระบบ'
    errCommonFeeIDNotFound = 'ไม่พบรหัสข้อมูลค่าส่วนกลาง'
    errCommonFeeIDProhibitSpecial  = 'รหัสข้อมูลค่าส่วนกลาง ห้ามมีอักขระพิเศษ หรือช่องว่าง'
    errCommonFeeNotNumber = 'รหัสข้อมูลส่วนกลาง ต้องเป็นตัวเลขเท่านั้น'

    errSearchTypeNotFound = 'ไม่พบประเภทการค้นหา'
    errSearchTpyeProhibitSpecial = 'ประเภทการค้นหา ห้ามมีอักขระพิเศษ หรือช่องว่าง'

}